**240840116057**

**Practical : 1 | Study the Data Analytics lifecycle and perform data acquisionfrom CSV Excel and Json files using Pandas.**

**Step - 1 Import Pandas library**

In [1]:
import pandas as pd                                 # Import Pandas Library

**Step - 2 Create a dataset**

In [2]:
data = {
    "ID": [ 101, 102, 103, 104, 105, 106, 107],
    "Name": ["Rahul", "Priya", "Amit", "Riya", "Karan", "Krisha", "Harry"],                               #Create Data
    "Age": [20, 21, 19, 20, 22, 24, 28],
    "City": ["Surat", "Navsari", "Valsad", "Bharuch", "Mumbai", "Bangalore", "Pune"],
     "Marks": [20, 90, 15, 50, 55, 65, 60]
}

**Step - 3 Create and display dataset**

In [3]:
df = pd.DataFrame(data)                # Convert into DataFrame
print(df)                              # To Print The DataFrame

    ID    Name  Age       City  Marks
0  101   Rahul   20      Surat     20
1  102   Priya   21    Navsari     90
2  103    Amit   19     Valsad     15
3  104    Riya   20    Bharuch     50
4  105   Karan   22     Mumbai     55
5  106  Krisha   24  Bangalore     65
6  107   Harry   28       Pune     60

**Step - 4 Save dataset as csv file**

In [4]:
df.to_csv("Students.csv", index=False)                     #Convert data into a CSV File


print("CSV file is created")

CSV file is created

**Step - 5 Save Dataframe As Excel**

In [5]:
df.to_excel("Students.xlsx", index=False)                     #Convert data into a EXCEL File


print("Excel file is created")

Excel file is created

**Step - 6 Save dataframe As Json**

In [6]:
df.to_json("Students.json", index=False)                  #Convert into jSON File

print("JSON file is created")

JSON file is created

**Step - 7 Read csv file**

In [7]:
df_csv = pd.read_csv("Students.csv")                      # Read CSV File
df_csv

    ID    Name  Age       City  Marks
0  101   Rahul   20      Surat     20
1  102   Priya   21    Navsari     90
2  103    Amit   19     Valsad     15
3  104    Riya   20    Bharuch     50
4  105   Karan   22     Mumbai     55
5  106  Krisha   24  Bangalore     65
6  107   Harry   28       Pune     60

In [8]:
df_excel = pd.read_excel("Students.xlsx")                  # Read Excel File
df_excel

    ID    Name  Age       City  Marks
0  101   Rahul   20      Surat     20
1  102   Priya   21    Navsari     90
2  103    Amit   19     Valsad     15
3  104    Riya   20    Bharuch     50
4  105   Karan   22     Mumbai     55
5  106  Krisha   24  Bangalore     65
6  107   Harry   28       Pune     60

In [9]:
df_json = pd.read_json("Students.json")                    # Read JSON File
df_json

    ID    Name  Age       City  Marks
0  101   Rahul   20      Surat     20
1  102   Priya   21    Navsari     90
2  103    Amit   19     Valsad     15
3  104    Riya   20    Bharuch     50
4  105   Karan   22     Mumbai     55
5  106  Krisha   24  Bangalore     65
6  107   Harry   28       Pune     60

**Step - 8 head**

In [10]:
df_csv.head()                                       # To Show First 5 Records

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     20
1  102  Priya   21  Navsari     90
2  103   Amit   19   Valsad     15
3  104   Riya   20  Bharuch     50
4  105  Karan   22   Mumbai     55

**Step - 9 tail**

In [11]:
df_csv.tail()                         # To Show Last 5 records

    ID    Name  Age       City  Marks
2  103    Amit   19     Valsad     15
3  104    Riya   20    Bharuch     50
4  105   Karan   22     Mumbai     55
5  106  Krisha   24  Bangalore     65
6  107   Harry   28       Pune     60

**Step - 10 information**

In [12]:
df_csv.info()                                     # Dsiplay informatiom

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

**Step - 11 descriptive statistics**

In [13]:
df_csv.describe()                                # Describe Stastical Memory

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  50.714286
std      2.160247   3.109126  26.049404
min    101.000000  19.000000  15.000000
25%    102.500000  20.000000  35.000000
50%    104.000000  21.000000  55.000000
75%    105.500000  23.000000  62.500000
max    107.000000  28.000000  90.000000

**Step - 12 shape**

In [14]:
df_csv.shape                               # display database shape(rows&columns)

(7, 5)

**Step - 13 multiple columns only**

In [15]:
df_csv.columns                            # display column names

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

**Step - 14 All data types**

In [16]:
df_csv.dtypes                             # display data types

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

**Step - 15 count missing values in columns**

In [17]:
df_csv.isnull().sum()                      # check null values

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

**Step - 16 display marks column**

In [18]:
df_csv["Marks"]                               # Dsiplay Particular  column

0    20
1    90
2    15
3    50
4    55
5    65
6    60
Name: Marks, dtype: int64

**Step - 17 display name and marks columns**

In [19]:
df_csv[["Name", "Marks"]]           #Display only the 'Name' and 'Marks' columns.

     Name  Marks
0   Rahul     20
1   Priya     90
2    Amit     15
3    Riya     50
4   Karan     55
5  Krisha     65
6   Harry     60

**Step - 18 filter records**

In [20]:
df_csv[df_csv["Marks"] > 50]                                    # To Filter Records

    ID    Name  Age       City  Marks
1  102   Priya   21    Navsari     90
4  105   Karan   22     Mumbai     55
5  106  Krisha   24  Bangalore     65
6  107   Harry   28       Pune     60

**Step - 19 calculate Averadge marks**

In [21]:
df_csv["Marks"].mean()                                       # To Dsiplay Average Marks

np.float64(50.714285714285715)

**Step - 20 Sort all the data**

In [22]:
df_csv.sort_values(by="Marks", ascending=False)               # To Sort Records

    ID    Name  Age       City  Marks
1  102   Priya   21    Navsari     90
5  106  Krisha   24  Bangalore     65
6  107   Harry   28       Pune     60
4  105   Karan   22     Mumbai     55
3  104    Riya   20    Bharuch     50
0  101   Rahul   20      Surat     20
2  103    Amit   19     Valsad     15

**Step - Display all data**

In [23]:
print(df_csv)                                             #Display DataFrame

    ID    Name  Age       City  Marks
0  101   Rahul   20      Surat     20
1  102   Priya   21    Navsari     90
2  103    Amit   19     Valsad     15
3  104    Riya   20    Bharuch     50
4  105   Karan   22     Mumbai     55
5  106  Krisha   24  Bangalore     65
6  107   Harry   28       Pune     60