**240840116057**

**Prac-2****(Perform Data Inspection, Cleaning, Hnadling Missing Values, remove duplicate values and data transformation using Pandas)**

**step - 1 : import Pandas Library**

In [1]:
import pandas as pd               # Import Pandas

**step-2:Create dataframe**

In [2]:
data = {
    "ID" : [101,102,103,104,104, 105, 106, 107],
    "Name" : ["Rahul", "Priya", "Amit", None, "Riya", "Ajay", "Naresh", "Jenil"],
    "Age" :   [20, 21, None, 20, 20, 22, 23, 28],
    "City" : ["Surat", "Navsari", "Surat", "Bharuch", "Bharuch", "Navsari", "Surat", "Ahemdabad"],
    "Marks" : [81, None, 78, 88, 88, 81, 90, 93]
}

df = pd.DataFrame(data)
print(df)

    ID    Name   Age       City  Marks
0  101   Rahul  20.0      Surat   81.0
1  102   Priya  21.0    Navsari    NaN
2  103    Amit   NaN      Surat   78.0
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   Jenil  28.0  Ahemdabad   93.0

**step 3:Inspect the dataset**

In [3]:
df.head()                                  # Display first 5 row of dataset

    ID   Name   Age     City  Marks
0  101  Rahul  20.0    Surat   81.0
1  102  Priya  21.0  Navsari    NaN
2  103   Amit   NaN    Surat   78.0
3  104   None  20.0  Bharuch   88.0
4  104   Riya  20.0  Bharuch   88.0

In [4]:
df.tail()                                  # Display last 5 row of dataset

    ID    Name   Age       City  Marks
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   Jenil  28.0  Ahemdabad   93.0

In [5]:
df.info()            # Dsiplay Info of Dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

In [6]:
df.describe()            # Display Stastical Info

           ID        Age      Marks
count    8.00   7.000000   7.000000
mean   104.00  22.000000  85.571429
std      2.00   2.886751   5.563486
min    101.00  20.000000  78.000000
25%    102.75  20.000000  81.000000
50%    104.00  21.000000  88.000000
75%    105.25  22.500000  89.000000
max    107.00  28.000000  93.000000

In [7]:
df.shape                # Display Dimensions

(8, 5)

In [8]:
df.dtypes               # Display DataTypes of DataSet

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

In [9]:
df.columns                         # Display all the columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

**step 4:check missing values**

In [10]:
df.isnull()                               # Display Missing Values

      ID   Name    Age   City  Marks
0  False  False  False  False  False
1  False  False  False  False   True
2  False  False   True  False  False
3  False   True  False  False  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False
7  False  False  False  False  False

In [11]:
df.isnull().sum()                          # Count Null Values

ID       0
Name     1
Age      1
City     0
Marks    1
dtype: int64

In [12]:
df.isnull().sum().sum()                          # Count NullValues for entire Dataset

np.int64(3)

**step 5:fill missing values**

In [13]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())         # Fill Missing Values

df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  81.000000
1  102   Priya  21.0    Navsari  85.571429
2  103    Amit   NaN      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahemdabad  93.000000

In [14]:
df["Age"] = df["Age"].fillna(df["Age"].mean())                # Fill Missing Value in Age Column

df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  81.000000
1  102   Priya  21.0    Navsari  85.571429
2  103    Amit  22.0      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahemdabad  93.000000

In [15]:
df["Name"] = df["Name"].fillna("Rudra")           # Fill Missing Value in Name

df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  81.000000
1  102   Priya  21.0    Navsari  85.571429
2  103    Amit  22.0      Surat  78.000000
3  104   Rudra  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahemdabad  93.000000

**step 6:Detect duplicate rercords**

In [16]:
df.duplicated()                         # Check Duplicate Value

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [17]:
df.duplicated().sum()                 # Count Duplicated Rows

np.int64(0)

**step 7: remove the dupolicate records**

In [18]:
df.drop_duplicates()                                       # Remove Duplicated Records

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  81.000000
1  102   Priya  21.0    Navsari  85.571429
2  103    Amit  22.0      Surat  78.000000
3  104   Rudra  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahemdabad  93.000000

**step 8:Rename the column.**

In [19]:
df.rename(columns={"Marks" : "Score"}, inplace=True)           # Rename Columns
df

    ID    Name   Age       City      Score
0  101   Rahul  20.0      Surat  81.000000
1  102   Priya  21.0    Navsari  85.571429
2  103    Amit  22.0      Surat  78.000000
3  104   Rudra  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahemdabad  93.000000

**step 9:Change data type**

In [20]:
df["Age"] = df["Age"].astype(int)          #Convert the age column from float to integer
df

    ID    Name  Age       City      Score
0  101   Rahul   20      Surat  81.000000
1  102   Priya   21    Navsari  85.571429
2  103    Amit   22      Surat  78.000000
3  104   Rudra   20    Bharuch  88.000000
4  104    Riya   20    Bharuch  88.000000
5  105    Ajay   22    Navsari  81.000000
6  106  Naresh   23      Surat  90.000000
7  107   Jenil   28  Ahemdabad  93.000000

**step 10:Create a new column**

In [21]:
df["Final_Score"] = df["Score"] + 5           #Create a new column.
df

    ID    Name  Age       City      Score  Final_Score
0  101   Rahul   20      Surat  81.000000    86.000000
1  102   Priya   21    Navsari  85.571429    90.571429
2  103    Amit   22      Surat  78.000000    83.000000
3  104   Rudra   20    Bharuch  88.000000    93.000000
4  104    Riya   20    Bharuch  88.000000    93.000000
5  105    Ajay   22    Navsari  81.000000    86.000000
6  106  Naresh   23      Surat  90.000000    95.000000
7  107   Jenil   28  Ahemdabad  93.000000    98.000000

**Step - 11 Convert text in uppercase**

In [22]:
df["Name"] = df["Name"].str.upper()                 # Convert Into UpperCase
df

    ID    Name  Age       City      Score  Final_Score
0  101   RAHUL   20      Surat  81.000000    86.000000
1  102   PRIYA   21    Navsari  85.571429    90.571429
2  103    AMIT   22      Surat  78.000000    83.000000
3  104   RUDRA   20    Bharuch  88.000000    93.000000
4  104    RIYA   20    Bharuch  88.000000    93.000000
5  105    AJAY   22    Navsari  81.000000    86.000000
6  106  NARESH   23      Surat  90.000000    95.000000
7  107   JENIL   28  Ahemdabad  93.000000    98.000000

**Step - 12 Convert text into lower case**

In [23]:
df["City"] = df["City"].str.lower()                  # Convert Text into LowerCase
df

    ID    Name  Age       City      Score  Final_Score
0  101   RAHUL   20      surat  81.000000    86.000000
1  102   PRIYA   21    navsari  85.571429    90.571429
2  103    AMIT   22      surat  78.000000    83.000000
3  104   RUDRA   20    bharuch  88.000000    93.000000
4  104    RIYA   20    bharuch  88.000000    93.000000
5  105    AJAY   22    navsari  81.000000    86.000000
6  106  NARESH   23      surat  90.000000    95.000000
7  107   JENIL   28  ahemdabad  93.000000    98.000000

**Step - 13 Remove extra space**

In [24]:
df["City"] = df["City"].str.strip()             # Remove Extra Space
df

    ID    Name  Age       City      Score  Final_Score
0  101   RAHUL   20      surat  81.000000    86.000000
1  102   PRIYA   21    navsari  85.571429    90.571429
2  103    AMIT   22      surat  78.000000    83.000000
3  104   RUDRA   20    bharuch  88.000000    93.000000
4  104    RIYA   20    bharuch  88.000000    93.000000
5  105    AJAY   22    navsari  81.000000    86.000000
6  106  NARESH   23      surat  90.000000    95.000000
7  107   JENIL   28  ahemdabad  93.000000    98.000000

**Step - 14 sort the dataset**

In [25]:
df.sort_values(by=["Final_Score"], inplace=True)              # Sort The DataSet Values
df

    ID    Name  Age       City      Score  Final_Score
2  103    AMIT   22      surat  78.000000    83.000000
0  101   RAHUL   20      surat  81.000000    86.000000
5  105    AJAY   22    navsari  81.000000    86.000000
1  102   PRIYA   21    navsari  85.571429    90.571429
3  104   RUDRA   20    bharuch  88.000000    93.000000
4  104    RIYA   20    bharuch  88.000000    93.000000
6  106  NARESH   23      surat  90.000000    95.000000
7  107   JENIL   28  ahemdabad  93.000000    98.000000

**Step - 15 Save the clean data**

In [26]:
df.to_csv('Cleaned_Students.csv', index=False)              # Save Cleaned DataSet
df

    ID    Name  Age       City      Score  Final_Score
2  103    AMIT   22      surat  78.000000    83.000000
0  101   RAHUL   20      surat  81.000000    86.000000
5  105    AJAY   22    navsari  81.000000    86.000000
1  102   PRIYA   21    navsari  85.571429    90.571429
3  104   RUDRA   20    bharuch  88.000000    93.000000
4  104    RIYA   20    bharuch  88.000000    93.000000
6  106  NARESH   23      surat  90.000000    95.000000
7  107   JENIL   28  ahemdabad  93.000000    98.000000